services:
  backend:
    init: true
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - rust_target:/app/target
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - REDIS_URL=redis://redis:6379
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  rust_target:
  node_modules:
  redis_data:
