version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - rust_target:/app/target
    ports:
      - "3000:3000"
    env_file:
      - .env.development
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
volumes:
  rust_target:
  node_modules:
