# fly.toml app configuration file generated for divine-thunder-7423 on 2023-06-27T22:18:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-thunder-7423"
primary_region = "nrt"

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

